# Generated by Django 6.0 on 2026-01-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_ai', '0004_chatlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
