# Generated by Django 6.0 on 2026-01-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_ai', '0005_chatlog_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
