# Generated by Django 6.0 on 2026-01-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_ai', '0007_remove_doctor_is_available_today_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
